### ISSUE TITLE
Rename `SemiFuture`

### ISSUE THREAD

**Issue by brycelelbach** [executors/futures#18]
I think we should not use the name `SemiFuture`. Rationale:

* It may be confusing to LEWG/concepts people. It invokes thoughts of the `SemiRegular` concept - e.g. some might think that a `SemiFuture` is a future that is `SemiRegular`. However, `SemiFuture` does not require `SemiRegular` (`DefaultConstructible` and `Copyable`), nor should it (unique futures are `Movable` not `Copyable`).
* It may be confusing to SG1 people as it's an unfamiliar term.

I'd prefer that we call this `Future`.

**Comment by brycelelbach** [comment]
@LeeHowes please review.

**Comment by griwes** [comment]
I kinda dislike `ContinuableFuture`, first because it's a mouthful, and second because for me futures aren't very useful when they aren't continuable, which is why I think this is the concept that should be called `Future`. Then we could call `SemiFuture` something like `BasicFuture` (this is a strawman name, since I don't have a better suggestion right now, but I don't like `SemiFuture` either).

**Comment by LeeHowes** [comment]
ContinuableFuture being called Future is slightly confusing because of the name clash with the traditional std::future, which then is clearly not a Future. A Future in the most general sense is a handle to yet-to-be computed data, so while they are mostly useful with continuations, they don't require them as a fundamental principle (or indeed get, fundamentally it need not specify how you get the value, only that there is one pending). BasicFuture (and indeed SemiFuture) do not expose what the limits of the semantics are.

The last discussion we had about this at Facebook was that we would like to rename SemiFuture to Future, but did not have a concise name for folly::Future, or fancy doing such a big global code- and memory-mod to rename it.

I don't have an especially good suggestion. I will confer with colleagues.

**Comment by brycelelbach** [comment]
We should perhaps look for precedence in other places - such as ranges, C++11 era concept proposals, and contemporary concept proposals.

`BasicFuture` and `ContinuableFuture` would be fine with me, as long as the `Basic` naming scheme isn't inconsistent with other work.

**Comment by brycelelbach** [comment]
Eric and Lee have convinced me this name is fine.
