### ISSUE TITLE
Can `.via` fail?

### ISSUE THREAD

**Issue by brycelelbach** [executors/futures#20]
- Can `.via` fail at compile time?
- Can `.via` fail at runtime (other than the polymorphic executor case if the answer to the above bullet was yes)?
- If so, what are the conditions in which it can fail? If the answer is yes, clearly this space is unbounded for user-defined executors.

**Comment by brycelelbach** [comment]
@LeeHowes please review.

**Comment by LeeHowes** [comment]
At compile time, certainly, given executor restrictions.

At runtime it fails under the same conditions in which .then fails. We should disallow multiple continuations, and .via is semantically a continuation (because that will sometimes be the right way to implement it, and we should not disallow it).

In that case it might fail with std::invalid_future_exception or something like that.

It might also throw under similar conditions to when then_execute throws, because in terms of the implementation, get_promise might be implemented in terms of similar state internally.

**Comment by brycelelbach** [comment]
> At compile time, certainly, given executor restrictions.

Do we know what these restrictions are? Some, I assume, depend on the future type and/or the executor type, and thus cannot be spelled out.

But are there any that we can spell out? Universal restrictions that can be described in terms of the standard executor properties? E.g. can we say something like "`.via(e)` is ill formed if `e` has executor property X" for all SemiFutures? If so, it would be unfortunate if every author of a SemiFuture had to require this property (e.g. if it was just boilerplate everyone had to repeat).

**Comment by RedBeard0531** [comment]
The runtime question seems tightly coupled to https://github.com/executors/executors/issues/373

**Comment by brycelelbach** [comment]
For additional discussion of *what* types of executors would lead to failure see #21.

Conclusion: yes, `.via` can fail at compile time or run time.

**Comment by LeeHowes** [comment]
Yes, the executor restrictions in #21 are what I have in mind. I *think* those are the only compile time failure cases, but I could be wrong.
