### ISSUE TITLE
Is a `ContinuableFuture<T>` convertible to ANY `SemiFuture<T>` type?

### ISSUE THREAD

**Issue by brycelelbach** [executors/futures#22]
See title.

**Comment by brycelelbach** [comment]
@LeeHowes please review.

**Comment by LeeHowes** [comment]
Interesting question. I think not, because we would need an executor value to be able to create a semifuture that completes in a particular way. It isn't even fundamental to require that all Futures have a paired SemiFuture - but if we do want to expose something like folly::Future<T>::semi() then we at least need to associate some semifuture type - it can be std::standard_semi_future though, which can create a private and trivial inline executor internally to trigger the completion.

**Comment by brycelelbach** [comment]
> I think not, because we would need an executor value to be able to create a semifuture that completes in a particular way.

Not sure that I understand this.

>  It isn't even fundamental to require that all Futures have a paired SemiFuture

I agree, I'd hate to require every ContinuableFuture to have to define/pick some SemiFuture type.

For now, let's just drop this convertibility requirement. It doesn't seem critical or fundamental. I only brought it up as it was on the whiteboard from the April 4th Facebook F2F.

**Comment by LeeHowes** [comment]
Dropping the requirement on the concept is probably fine, but std::continuable_future should be convertible to std::semi_future and std::semi_future should be constructible from any continuable future.
