### ISSUE TITLE
Is `.then` necessary or convenient?

### ISSUE THREAD

**Issue by brycelelbach** [executors/futures#23]
Assuming we go forward with our proposed change to `then_execute`'s signature and our addition of `deferred_execute`, one way of writing `.then` is as follows:

```
template <typename Callable>
auto then(Callable g)
{
  auto [trigger, future] = exec.deferred_execute(g);
  exec.then_execute(trigger, *this);
  return future;
}
```

The motivation for this model (the "Javascript" model if you will, as it is closer to what Javascript does, similar to David Sankel's future proposal) is that it's necessary to enable certain types of futures, [such as a GPU-based future](https://github.com/executors/futures-impl/blob/master/archetypes/cuda_stream_future.cu#L225).

More traditional future/promise models (i.e. the "C++ Concurrency TS v1" model) don't necessarily need this, but it seems like it would not be harmful for them to be implemented this way.

This raises some questions:

* Is the above implementation of `.then` suitable for all future types?
* Are there cases where someone's future type might want to do something other than the above implementation in their `.then`?
* Is `.then` just syntax sugar that we need because we want to do chaining and we don't have unicorn call syntax?

**Comment by brycelelbach** [comment]
@LeeHowes and @jaredhoberock please review.

**Comment by dhollman** [comment]
I thought that we had discuss the GPU executor as a specific place where this sort of thing wasn't ideal — e.g., where you might want to put the continuation directly on the same queue of the agent responsible for the asynchronous provider tied to the future (i.e., `*this`) without creating any intermediate state. That doesn't really work here, because you've separated the future you're returning from the future you're continuing. (I think that was the basic argument agains the "all future types" thing? @LeeHowes can probably state it more eloquently and/or correct me.)

**Comment by LeeHowes** [comment]
That's not my understanding of the implementation. I thought we were working with:
```
template <typename Callable>
auto then(Callable g)
{
  auto trigger = exec.get_promise<value_type>();
  auto future = trigger.get_future();
  return exec.then_execute(g, future);
}

```

Which does not change the signature of then_execute, and merely adds a PromiseExecutor concept with get_promise on it (or make_promise as Chris K reasonably suggested).

I don't think this is fully general. We may want a onway_executor to be supported.

Additionally, I argued, and strongly believe, that then_execute should take a ready_future type as the callable parameter. We should have such a .then on the future, (continue_with, maybe) but we also want a .then that takes a value callable - so that one would have to wrap the callable, simply something like:
```
template <typename Callable>
auto then(Callable g)
{
  auto trigger = exec.get_promise<value_type>();
  auto future = trigger.get_future();
  return exec.then_execute([](auto&& param){return g(param.get()), future);
}

```

> Is .then just syntax sugar that we need because we want to do chaining and we don't have unicorn call syntax?

Yes. What the above means in my view is that fundamentally we need .continue_with, taking the executor's ready_future type as the continuation parameter, on every future. It can be a method or a free function, it doesn't matter.

.then can be build trivially on that:
```
template <typename Callable>
auto then(Callable value_callable)
{
  return continue_with([](auto&& param){return value_callable(param.get()), future);
}

```

That is using the public interface of the future, so then can easily be a free function, or a free operator. Other variants of then are similarly valuable free functions we could build on that same primitive. So yes, it is not fundamental, it's only there fore syntactic convenience because we don't have UCS for chaining. We could, of course, consider supporting:
`
auto newF = f.continue_with(some ready-future continuation) | [](int a){return float(a) + 1;} | [](float b){ return b + 1.0f;};
`

**Comment by dhollman** [comment]
> We can specialise to drop the extra work

That was basically my point. I was contradicting the idea that all futures can work exactly the same way w.r.t. `.then()`, as (I think) Bryce was suggesting. Some futures will have to specialize something differently than the implementation Bryce gave (the name of the thing they specialize orthogonal to my point, I think).

**Comment by brycelelbach** [comment]
I wasn't suggesting that all futures work the same way - I just wanted us to think about how `.then` might be useful outside of interface benefits.

**Comment by brycelelbach** [comment]
Okay, answer is no - in particular for specialization. This is useful for CUDA futures, for example.
