### ISSUE TITLE
Can shared future continuations modify the state?

### ISSUE THREAD

**Issue by brycelelbach** [executors/futures#26]
The answer should probably be no. We should disallow continuations that take their argument by non-const lvalue reference.

This has a nice side effect - unique futures have to disallow such continuations anyways, although const lvalue reference parameters are fine.

E.g.

```
void f(std::string& s);

int main()
{
  std::string s = "hello";

  f(std::move(s)); // COMPILE FAILURE.
}
```

```
void f(std::string const& s);

int main()
{
  std::string s = "hello";

  f(std::move(s)); // Ok.
}
```

**Comment by brycelelbach** [comment]
@LeeHowes please review.

**Comment by griwes** [comment]
I honestly don't see a use case for modifying the state.

IMHO a future, as far as it is observable, after it has an associated value, it should not ever change. (The observability comment is for the sake of unique future that'll probably move the value when accessed, but subsequent accesses of the value should be at the very least unspecified and possibly undefined, which makes it effectively a linear type.)

**Comment by jaredhoberock** [comment]
I think we should not be prescriptive about this. Once the continuation begins execution, the original future seems irrelevant to me because it no longer exists. If the continuation wants to mutate the predecessor, that's its business, and it's the responsibility of the continuation author to avoid races.

**Comment by dhollman** [comment]
>  I would want to avoid the requirement that it work.

+1.

Also +1 to Bryce's point that the future implementer should be able to move the value into the continuation arguments. I don't think it's overly prescriptive to say that continuations using non-const reference arguments won't work in generic code. If we don't prescribe this, we are *de facto* prescribing that using a `move` on the `future` implementer's side _won't_ work.

**Comment by brycelelbach** [comment]
So it sounds like the conclusion is that we don't want to disallow this.

This has some impact on #27. Let's continue any discussion there.

**Comment by LeeHowes** [comment]
If we don't disallow it here, why disallow it for unique_future?

I am wary of branching these two too much. What if I want to implement shared_future by copying the shared state, but otherwise being identical to a unique_future. In that case I have the same reference semantics relative to the shared state in either case. I'm not sure I want to require that the shared_state of the shared future stick around after destruction, which reference semantics would imply.

For example, if I do:
```
future f;
future f2;
{
  shared_future s;
  f = s.then(...);
  f2 = s.then(...);
}
```

Now, should the shared state of s remain present for the reference parameters? Once s is destroyed it will satisfy all still-alive promises for f and f2 immediately by copyable call to set_value. That call to set_value would internally move directly into the callback.

So I think my position on this is that we should always support r and l-value parameters, and it is up to the call wrapper to pass a reference to a temporary if that is the requirement, or to move the temporary in after a copy for an r-value version off a shared future.

**Comment by RedBeard0531** [comment]
> What if I want to implement shared_future by copying the shared state, but otherwise being identical to a unique_future?

Wouldn't that require a Copyable T, making shared_future<unique_ptr<Foo>> illegal? I'm not sure if that is a valid implementation.

**Comment by LeeHowes** [comment]
I think maybe that is illegal. Otherwise we have to disallow the value parameter case in that example as well, because we can't copy into the parameter. The only options are & and const &. It'll be very confusing to use if we have to go that far.

**Comment by RedBeard0531** [comment]
Move-only types seem important to support in Futures. It seems extremely limiting to say that Future<T> requires that T is Copyable.

We should probably define how the callbacks will be invoked rather than their allowed signatures. eg `require is_invocable<Callback, T&>` for SharedFuture and `is_invocable<Callback, T&&>` for UniqueFuture. For a copyable T, that allows the Callback their choice of by-ref vs by-val. It also supports `auto&&` and anything that T can implicitly convert to.

**Comment by dhollman** [comment]
> So I think my position on this is that we should always support r and l-value parameters, and it is up to the call wrapper to pass a reference to a temporary if that is the requirement, or to move the temporary in after a copy for an r-value version off a shared future.

I think if you ask for a parameter by r-value reference (in any context), it's pretty clear that you didn't mean "copy and move it"; otherwise, you would have just asked for it by value.  I don't know of any standard library facility that implicitly converts something that has to be a copy into something that looks like a move.  The opposite also doesn't happen for non-const lvalue references — a move doesn't get converted into a copy unless there is a const lvalue reference copy constructor available.  An example of the latter behavior is `vector::push_back`, where the `T&&` overload will not participate in overload resolution if `T` has (only) a non-const reference copy constructor. Thus, I think it's totally reasonable for `shared_future<T>.then([](T&&){ });` and `unique_future<T>.then([](T&){ });` to be compile-time errors.

> We should probably define how the callbacks will be invoked rather than their allowed signatures. eg `require is_invocable<Callback, T&>` for SharedFuture and `is_invocable<Callback, T&&>` for UniqueFuture.

Agreed.

> For example, if I do:

```
future f;
future f2;
{
  shared_future s;
  f = s.then(...);
  f2 = s.then(...);
}
```
> Now, should the shared state of s remain present for the reference parameters?

But doesn't the copyability of `shared_future` essentially imply some sort of reference counting anyway? A continuation that acts on a non-const lvalue-reference effectively holds a reference that is part of that count.  Even if the `shared_future` continuations take their parameter by value, you still need to keep something around after the destruction of `s` because the continuation may not have been invoked yet.

An alternative is to say that `T&` parameters aren't guaranteed to compile in generic code with shared futures, and that `T const&` parameters may be copies. I know it's tempting to just punt on this one and not impose any requirements, but that makes life much more difficult on `future` implementers — they then need to use detection, etc. to determine which kind of call to make and then potentially keep values around so that references are valid. (If we don't say anything, I think the implication is that all signatures have to work as expected in generic code). In other words, I don't see how we can avoid imposing some requirement here either way, whether it's explicit or by omission.

**Comment by dhollman** [comment]
Tangentially related prior art: P0518r1 (which got accepted into IS17)

**Comment by brycelelbach** [comment]
@LeeHowes 

> If we don't disallow it here, why disallow it for unique_future?

Because that's how rvalue references work. You can't bind rvalue references to non-const lvalue references; that is a conscious design choice in C++.
