### ISSUE TITLE
Exception handling

### ISSUE THREAD

**Issue by LeeHowes** [executors/futures#7]
In Jacksonville P0904R0 and P0701R2 both talked about error handling with continuations.

At Facebook we strongly favour an expected-style error handling mechanism, as a primary means.
Based on feedback during the meeting, however, it is clear that a significant portion of people in the room want the simplest, default, means of chaining to be value-based, with error bypass.

I would then propose the following:
  * StandardFuture<T>::then accepts a continuation taking T&&, and returning T, expected<T, exception_ptr> or StandardSemiFuture<T> (this last point because the executor on the returned future does not matter because it is unpacked into the chain).
  * StandardFuture<T>::thenExpected accepts a continuation taking expected<T, exception_ptr>&& and returning as above.
  * StandardFuture<T>::thenError accepts an exception_ptr.

then can be defined as if:
```
StandardFuture<T>::then(F&& func) {
 return thenExpected([func = std::move(func)](expected<T, exception_ptr>&& e) {
    if(e.hasValue()) {
      return func(e.value());
    } else {
      throw e.exception();
    }
  });
}
```

and thenError as:
```
StandardFuture<T>::thenError(F&& func) {
 return thenExpected([func = std::move(func)](expected<T, exception_ptr>&& e) {
    if(e.hasValue()) {
      return std::move(e);
    } else {
      return func(e.exception());
    }
  });
}

```

Or similar. The names should be explicit to allow:
```
f.then([](auto&& p) {
});
```

To work without overload resolution issues.

**Comment by LeeHowes** [comment]
While the above is certainly optimal, and using expected types widely has significantly strengthened Facebook's codebase, now that I properly read the latest update std::expected paper it seems to be taking a slow path into the standard. We therefore presumably cannot assume that we can depend on it. This looks like another example of a gap in the library pushing decisions in another part into a corner if we are to move forward at all.

In which case what I suggest is that we ensure the API is consistent with use of an expected type, so we can easily add it later once it becomes available.

**Comment by jaredhoberock** [comment]
Even if `std::expected` was a standard, it's unlikely that e.g. a GPU executor could use it per se. Instead, it would have to use some similar type with the proper annotations (i.e. CUDA's `__host__ __device__`) necessary for generating GPU code.

But beyond those concerns, to the degree possible it's generally valuable to avoid being too prescriptive about the concrete types that must appear in interfaces and instead focus on requirements for those types. So, instead of demanding `std::expected`, we could demand a hypothetical `Expected`, with requirements that the anticipated `std::expected` would fulfill.

**Comment by LeeHowes** [comment]
In that case we'd have to at least define that for some expected type E that is the  parameter and result of a task. That type should be associated with the executor such that the executor knows how to pack and unpack the value as necessary, so the exception and value both get passed on if the next task does not match and so on.

Either way, a change for V2.

**Comment by LeeHowes** [comment]
We know what we are doing for executors.

Any reason to not expose exactly the same Promise-like callable as the parameter to then.

Propagation works too based on presence or absence.

Trait on executor is pending exception handling work. Whether we need to use it to block exception-taking callbacks at this level if open to question.

**Comment by LeeHowes** [comment]
I've updated with some wording based on the executors discussion. They should be properly aligned at some point.

**Comment by brycelelbach** [comment]
To clarify, the model is:

Given `g = f.then(G)`:

If `f` has a value, `G(v)` is called.

If `f` fails with error `e`:
* If `G(future_error_t, e)` is well-formed, it is called and the future `g` is made ready with the value or error of the call.
* Otherwise, the future `g` is made ready with the error `e`.

**Comment by LeeHowes** [comment]
I think the final agreement was that "is well-formed" applied to both sides. I'm *more* concerned about the error case accidentally skipping than the value case. I could be persuaded that the error case has a well-defined signature, and because exception_ptr behaves like shared_ptr actually we should accept all possible overloads trivially such that it is basically never not well-formed. 

In general, i don't like this "is-well-formed" approach to decision making for these primitives.

Either way, the intent here is to defer to the underlying executor rules, so whatever we put in here is only to be complete. We should have an editorial note saying that the intent is to be consistent and only put it in the spec once.

**Comment by RedBeard0531** [comment]
On previous calls, I thought the consensus was trending toward `f.then()` only being for the success case with other names (strawmen: `on_error()` and `on_completion()`) for when you want to be called in other cases. Are we moving away from that?

It seems reasonable for `Future::then()` to have a different, more sugary, API than `executor::then_execute` since the former is intended to be used directly by end users while the latter is primarily called by library code. Of course we should ensure that all continuation methods can be implemented by calling `then_execute`, and that the success-or-error continuation uses a compatible API for passing results. But that doesn't mean that it should get the privileged `then` name.

**Comment by dhollman** [comment]
@RedBeard0531 See if #48 and #49 provides the sugar you want here

**Comment by brycelelbach** [comment]
From the NVIDIA F2F meeting:

```
g = f.then(G);

// If `f` has a value, `G(val)` is called.

// If `f` fails with error `err`:
// * If `G(future_error, err)` is well-formed, it is called and the future `g` is made ready with the value or error of the call.
//    * Requires: `is_same_v<decltype(G(future_error_t, err)), decltype(G(val))>` 
// * Otherwise, the future `g` is made ready with the error `err` (future propagation).

struct future_error_t {};
inline future_error_t const future_error{};

template <typename T>
struct FutureContinuation // Concept
{
  // We already discussed the allowed signatures/parameter passing styles;
  // for brevity I'll just write by value here.
  R operator()(T t); // Required.
  R operator()(future_error_t, exception_ptr err); // Optional.
};

// Alternative that Lee suggested: ready_future concept, and the continuation gets a ready_future.

// Michal: The above `FutureContinuation` is fine for a low-level API for executors,
// but for futures I'd like a .then and a .on_error

// Bryce: One objection, I don't want future authors to have to package these up into the executor-style continuation

// Answer:
unique_future f;
std::move(f).then(on_value_error(g, h));

// Michal: We're saying .then would still take FutureContinuations, on_value_error just produces one.

// Poll: future<future<>> unwrapping is a version 1 feature.
// SF F N A SA
// 1 1 2 0 3

// For the F/SFs: Why?
// Completeness.

// Poll: .then and then_execute take FutureContinuation (conceptually a pair of callables, currently
// defined as what is in executors), we do error handling/propagation as above (the same thing Executors do),
// and we don't do unwrapping, we provide some helper functions (then_error, then_value, and then_value_error
// which don't unwrap) in version 1 (Rapperswil) of the paper.
// SF F N A SA
// 4 3 0 0 0
```

See also:
* Issue for adding the `FutureContinuation` helper functions: #48 

Action Items:
* [ ] Implement wording for the error handling model (this should be the same as what is in executors, but let's describe it here as well for completeness).

**Comment by LeeHowes** [comment]
Merged text in from executors paper in https://github.com/executors/futures/pull/58

**Comment by LeeHowes** [comment]
PR https://github.com/executors/futures/pull/58 merged.

Closing.
